# Generated by Django 2.2.2 on 2020-04-18 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='day',
            name='title',
            field=models.CharField(max_length=200, verbose_name='タイトル'),
        ),
    ]
